/**
 * IntentMapWriter — Generates and incrementally updates `.orchestration/intent_map.md`.
 *
 * Purpose: Maps high-level business intents to physical files and AST nodes.
 *          When a manager asks "Where is the billing logic?", this file provides the answer.
 *
 * Update Pattern: Incrementally updated when INTENT_EVOLUTION mutations occur
 *                 (as classified by SemanticClassifier).
 *
 * Alignment: TRP1 Challenge Week 1 — Data Model item #3 (.orchestration/intent_map.md)
 *            Research doc: "Formalizing the AST-to-Intent Correlation"
 */

import * as fs from "node:fs"
import * as path from "node:path"

import type { AgentTraceRecord } from "./TraceLogger"
import { MutationClass } from "./SemanticClassifier"

// ── Types ────────────────────────────────────────────────────────────────────

/** A single file entry within the intent map. */
export interface IntentMapFileEntry {
	/** Relative path from workspace root */
	relativePath: string

	/** SHA-256 content hash for spatial independence */
	contentHash: string

	/** 1-indexed start line */
	startLine: number

	/** 1-indexed end line */
	endLine: number

	/** Mutation class that triggered this mapping */
	mutationClass: MutationClass

	/** ISO timestamp of last update */
	lastUpdated: string

	/** Git SHA at the time of recording */
	gitSha: string
}

/** All file entries grouped under a single intent. */
export interface IntentMapSection {
	/** Intent ID (e.g., "INT-001") */
	intentId: string

	/** Human-readable intent name (resolved from active_intents.yaml or trace) */
	intentName: string

	/** Ordered list of file entries associated with this intent */
	files: IntentMapFileEntry[]
}

/** The full in-memory representation of intent_map.md. */
export interface IntentMap {
	sections: IntentMapSection[]
}

/** Result of an update operation. */
export interface IntentMapUpdateResult {
	success: boolean
	/** Path to the generated file */
	filePath: string
	/** Number of intent sections in the map */
	intentCount: number
	/** Total number of file entries across all intents */
	fileEntryCount: number
	/** Whether this was a new file or an incremental update */
	isNewFile: boolean
	error?: string
}

// ── Constants ────────────────────────────────────────────────────────────────

const INTENT_MAP_FILE = ".orchestration/intent_map.md"

const HEADER = [
	"# Intent Map — Spatial Index",
	"",
	"> Auto-generated by the Hook Engine. Maps business intents to physical files and AST ranges.",
	"> Updated incrementally when `INTENT_EVOLUTION` mutations occur.",
	"> Content hashes provide spatial independence — if code moves, the hash still tracks it.",
	"",
	`> Last regenerated: %%TIMESTAMP%%`,
	"",
	"---",
	"",
].join("\n")

const TABLE_HEADER = [
	"| File | Content Hash | Lines | Mutation | Git SHA | Last Updated |",
	"|------|-------------|-------|----------|---------|--------------|",
].join("\n")

// ── IntentMapWriter ──────────────────────────────────────────────────────────

export class IntentMapWriter {
	/**
	 * Incrementally updates `.orchestration/intent_map.md` from a new trace record.
	 *
	 * Called from HookEngine.runPostHooks() after TraceLogger records a trace.
	 * Only updates the map when the mutation is INTENT_EVOLUTION (per spec).
	 *
	 * @param trace   The Agent Trace record just persisted
	 * @param cwd     Workspace root
	 * @returns       Update result with stats
	 */
	static update(trace: AgentTraceRecord, cwd: string): IntentMapUpdateResult {
		const mapPath = path.join(cwd, INTENT_MAP_FILE)

		try {
			// Only update on INTENT_EVOLUTION mutations (spec requirement)
			if (trace.mutation.mutation_class !== MutationClass.INTENT_EVOLUTION) {
				return {
					success: true,
					filePath: mapPath,
					intentCount: 0,
					fileEntryCount: 0,
					isNewFile: false,
				}
			}

			// Extract the intent ID from the trace's related array (the "golden thread")
			const intentId = IntentMapWriter.extractIntentId(trace)
			if (!intentId) {
				return {
					success: true,
					filePath: mapPath,
					intentCount: 0,
					fileEntryCount: 0,
					isNewFile: false,
				}
			}

			// Load existing map (or create empty)
			const isNewFile = !fs.existsSync(mapPath)
			const map = isNewFile ? { sections: [] } : IntentMapWriter.parseMap(mapPath)

			// Build new file entries from the trace
			const newEntries = IntentMapWriter.traceToEntries(trace)

			// Merge into the map
			IntentMapWriter.mergeEntries(map, intentId, newEntries)

			// Resolve intent names from active_intents.yaml if available
			IntentMapWriter.resolveIntentNames(map, cwd)

			// Write the updated map
			IntentMapWriter.writeMap(map, mapPath)

			const totalFiles = map.sections.reduce((sum, s) => sum + s.files.length, 0)

			console.log(
				`[IntentMapWriter] Updated intent_map.md: ${map.sections.length} intent(s), ` +
					`${totalFiles} file mapping(s) | trigger: ${intentId}`,
			)

			return {
				success: true,
				filePath: mapPath,
				intentCount: map.sections.length,
				fileEntryCount: totalFiles,
				isNewFile,
			}
		} catch (error) {
			const errorMessage = error instanceof Error ? error.message : String(error)
			console.error(`[IntentMapWriter] Failed to update intent_map.md: ${errorMessage}`)
			return {
				success: false,
				filePath: mapPath,
				intentCount: 0,
				fileEntryCount: 0,
				isNewFile: false,
				error: errorMessage,
			}
		}
	}

	/**
	 * Regenerates intent_map.md from the full agent_trace.jsonl ledger.
	 * Useful for rebuilding the map from scratch (e.g., after corruption).
	 */
	static regenerate(cwd: string): IntentMapUpdateResult {
		const tracePath = path.join(cwd, ".orchestration", "agent_trace.jsonl")
		const mapPath = path.join(cwd, INTENT_MAP_FILE)

		try {
			if (!fs.existsSync(tracePath)) {
				return {
					success: false,
					filePath: mapPath,
					intentCount: 0,
					fileEntryCount: 0,
					isNewFile: true,
					error: "agent_trace.jsonl not found — no trace data to build from",
				}
			}

			const raw = fs.readFileSync(tracePath, "utf-8")
			const lines = raw.split("\n").filter((l) => l.trim().length > 0)

			const map: IntentMap = { sections: [] }

			for (const line of lines) {
				try {
					const trace = JSON.parse(line) as AgentTraceRecord
					if (trace.mutation?.mutation_class !== MutationClass.INTENT_EVOLUTION) {
						continue
					}

					const intentId = IntentMapWriter.extractIntentId(trace)
					if (!intentId) {
						continue
					}

					const entries = IntentMapWriter.traceToEntries(trace)
					IntentMapWriter.mergeEntries(map, intentId, entries)
				} catch {
					// Skip malformed lines
				}
			}

			IntentMapWriter.resolveIntentNames(map, cwd)
			IntentMapWriter.writeMap(map, mapPath)

			const totalFiles = map.sections.reduce((sum, s) => sum + s.files.length, 0)

			console.log(
				`[IntentMapWriter] Regenerated intent_map.md from ${lines.length} trace records: ` +
					`${map.sections.length} intent(s), ${totalFiles} file mapping(s)`,
			)

			return {
				success: true,
				filePath: mapPath,
				intentCount: map.sections.length,
				fileEntryCount: totalFiles,
				isNewFile: true,
			}
		} catch (error) {
			const errorMessage = error instanceof Error ? error.message : String(error)
			console.error(`[IntentMapWriter] Failed to regenerate intent_map.md: ${errorMessage}`)
			return {
				success: false,
				filePath: mapPath,
				intentCount: 0,
				fileEntryCount: 0,
				isNewFile: true,
				error: errorMessage,
			}
		}
	}

	// ── Extraction helpers ───────────────────────────────────────────────────

	/** Extracts the intent ID from the trace record's related array ("golden thread"). */
	static extractIntentId(trace: AgentTraceRecord): string | null {
		for (const file of trace.files) {
			for (const conv of file.conversations) {
				for (const rel of conv.related) {
					if (rel.type === "specification" && rel.value) {
						return rel.value
					}
				}
			}
		}
		return null
	}

	/** Converts an AgentTraceRecord into IntentMapFileEntry items. */
	static traceToEntries(trace: AgentTraceRecord): IntentMapFileEntry[] {
		const entries: IntentMapFileEntry[] = []

		for (const file of trace.files) {
			for (const conv of file.conversations) {
				for (const range of conv.ranges) {
					entries.push({
						relativePath: file.relative_path,
						contentHash: range.content_hash,
						startLine: range.start_line,
						endLine: range.end_line,
						mutationClass: trace.mutation.mutation_class as MutationClass,
						lastUpdated: trace.timestamp,
						gitSha: trace.vcs.revision_id,
					})
				}
			}
		}

		return entries
	}

	// ── Map merge logic ──────────────────────────────────────────────────────

	/**
	 * Merges new file entries into the map under the given intent.
	 * If a file already exists under the intent, its entry is updated (upsert).
	 */
	static mergeEntries(map: IntentMap, intentId: string, newEntries: IntentMapFileEntry[]): void {
		let section = map.sections.find((s) => s.intentId === intentId)

		if (!section) {
			section = {
				intentId,
				intentName: intentId, // Will be resolved later
				files: [],
			}
			map.sections.push(section)
		}

		for (const entry of newEntries) {
			// Upsert: replace existing entry for the same file, or append
			const existingIndex = section.files.findIndex((f) => f.relativePath === entry.relativePath)

			if (existingIndex >= 0) {
				section.files[existingIndex] = entry
			} else {
				section.files.push(entry)
			}
		}

		// Sort files alphabetically within each section
		section.files.sort((a, b) => a.relativePath.localeCompare(b.relativePath))
	}

	// ── Intent name resolution ───────────────────────────────────────────────

	/** Resolves human-readable names from active_intents.yaml for all sections. */
	static resolveIntentNames(map: IntentMap, cwd: string): void {
		const intentsPath = path.join(cwd, ".orchestration", "active_intents.yaml")

		let intentNames: Map<string, string> = new Map()

		try {
			if (fs.existsSync(intentsPath)) {
				const raw = fs.readFileSync(intentsPath, "utf-8")
				intentNames = IntentMapWriter.parseIntentNames(raw)
			}
		} catch {
			// Gracefully degrade — keep the ID as the name
		}

		for (const section of map.sections) {
			const resolved = intentNames.get(section.intentId)
			if (resolved) {
				section.intentName = resolved
			}
		}
	}

	/** Simple YAML-like parser for intent names (avoids heavy YAML dependency). */
	static parseIntentNames(yamlContent: string): Map<string, string> {
		const names = new Map<string, string>()
		const idPattern = /^\s*-?\s*id:\s*"?([^"]+)"?\s*$/
		const namePattern = /^\s*name:\s*"?([^"]+)"?\s*$/

		const lines = yamlContent.split("\n")
		let currentId: string | null = null

		for (const line of lines) {
			const idMatch = idPattern.exec(line)
			if (idMatch) {
				currentId = idMatch[1].trim()
				continue
			}

			const nameMatch = namePattern.exec(line)
			if (nameMatch && currentId) {
				names.set(currentId, nameMatch[1].trim())
				currentId = null
			}
		}

		return names
	}

	// ── Markdown serialization ───────────────────────────────────────────────

	/** Writes the intent map to disk as Markdown. */
	static writeMap(map: IntentMap, mapPath: string): void {
		const dir = path.dirname(mapPath)
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true })
		}

		const content = IntentMapWriter.serializeMap(map)
		fs.writeFileSync(mapPath, content, "utf-8")
	}

	/** Serializes the full IntentMap to a Markdown string. */
	static serializeMap(map: IntentMap): string {
		const parts: string[] = []

		// Header with current timestamp
		parts.push(HEADER.replace("%%TIMESTAMP%%", new Date().toISOString()))

		// Sort sections by intent ID
		const sorted = [...map.sections].sort((a, b) => a.intentId.localeCompare(b.intentId))

		for (const section of sorted) {
			parts.push(`## ${section.intentId}: ${section.intentName}`)
			parts.push("")

			if (section.files.length === 0) {
				parts.push("_No file mappings recorded yet._")
				parts.push("")
				continue
			}

			parts.push(TABLE_HEADER)

			for (const file of section.files) {
				const hashShort =
					file.contentHash.length > 20 ? file.contentHash.substring(0, 20) + "…" : file.contentHash
				const shaShort = file.gitSha.length > 8 ? file.gitSha.substring(0, 8) : file.gitSha
				const timeShort = file.lastUpdated.substring(0, 19)

				parts.push(
					`| \`${file.relativePath}\` | \`${hashShort}\` | ${file.startLine}–${file.endLine} | ${file.mutationClass} | \`${shaShort}\` | ${timeShort} |`,
				)
			}

			parts.push("")
		}

		if (sorted.length === 0) {
			parts.push("_No intent-file mappings recorded yet. Mappings appear after INTENT_EVOLUTION mutations._")
			parts.push("")
		}

		return parts.join("\n")
	}

	// ── Markdown parsing ─────────────────────────────────────────────────────

	/** Parses an existing intent_map.md back into the in-memory data structure. */
	static parseMap(mapPath: string): IntentMap {
		const map: IntentMap = { sections: [] }

		if (!fs.existsSync(mapPath)) {
			return map
		}

		try {
			const content = fs.readFileSync(mapPath, "utf-8")
			return IntentMapWriter.parseMapContent(content)
		} catch {
			// If parsing fails, return empty map (will be regenerated)
			return map
		}
	}

	/** Parses the Markdown content string into an IntentMap. */
	static parseMapContent(content: string): IntentMap {
		const map: IntentMap = { sections: [] }

		// Split by intent section headers: ## INT-XXX: Name
		const sectionPattern = /^## ([A-Z]+-\d+):\s*(.+)$/gm
		const matches: Array<{ intentId: string; intentName: string; startIndex: number }> = []

		let match: RegExpExecArray | null
		while ((match = sectionPattern.exec(content)) !== null) {
			matches.push({
				intentId: match[1],
				intentName: match[2].trim(),
				startIndex: match.index,
			})
		}

		for (let i = 0; i < matches.length; i++) {
			const m = matches[i]
			const nextStart = i + 1 < matches.length ? matches[i + 1].startIndex : content.length
			const sectionContent = content.substring(m.startIndex, nextStart)

			const section: IntentMapSection = {
				intentId: m.intentId,
				intentName: m.intentName,
				files: IntentMapWriter.parseTableRows(sectionContent),
			}

			map.sections.push(section)
		}

		return map
	}

	/** Parses Markdown table rows within a section into IntentMapFileEntry items. */
	static parseTableRows(sectionContent: string): IntentMapFileEntry[] {
		const entries: IntentMapFileEntry[] = []

		// Match table data rows (skip header and separator)
		const rowPattern =
			/^\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|\s*(\d+)[–-](\d+)\s*\|\s*(\S+)\s*\|\s*`([^`]+)`\s*\|\s*(\S+)\s*\|$/gm

		let rowMatch: RegExpExecArray | null
		while ((rowMatch = rowPattern.exec(sectionContent)) !== null) {
			entries.push({
				relativePath: rowMatch[1],
				contentHash: rowMatch[2].replace("…", ""), // Truncated hashes get preserved as-is
				startLine: parseInt(rowMatch[3], 10),
				endLine: parseInt(rowMatch[4], 10),
				mutationClass: rowMatch[5] as MutationClass,
				gitSha: rowMatch[6],
				lastUpdated: rowMatch[7],
			})
		}

		return entries
	}
}
